openapi: "3.0.2"

info:
  title: "Checkout SVC Project"
  description: "The service responsible for checkout"
  contact:
    name: Checkout Service
    email: checkout.svc.test@gmail.com
    url: https://checkout-svc.herokuapp.com/
  version: "0.1.0"

servers:
  - url: https://checkout-svc.herokuapp.com/
    description: Modern local version of api.

tags:
  - name: Auth
    description: Auth
  - name: Products
    description: |
      Related getting products on the service
  - name: Cart
    description: |
      Related adding, deleting  products on a cart and checkout process

paths:
  /api/v1/auth/register:
    $ref: "./auth/paths.yaml#/register"
  /api/v1/auth/login:
    $ref: "./auth/paths.yaml#/login"
  /api/v1/products/{integration}/{externalId}:
    $ref: "./products/paths.yaml#/product"
  /api/v1/cart/products:
    $ref: "./carts/paths.yaml#/products"
  /api/v1/cart/products/{externalId}:
    $ref: "./carts/paths.yaml#/deleteProduct"
  /api/v1/cart/checkout:
    $ref: "./carts/paths.yaml#/checkout"

components:
  securitySchemes:
    BearerAuth: # Possibly it should be oauth
      type: http
      scheme: bearer
      bearerFormat: JWT
